# Consumer keep-rules for the adhan-playback module.
#
# R8 is currently OFF for this app (android.enableShrinkResourcesInReleaseBuilds
# and enableMinifyInReleaseBuilds are both false). These rules ship with the
# module so that turning it on later is a one-line change rather than a debugging
# session — a silent adhan is the hardest possible failure to notice.
#
# `consumerProguardFiles` in build.gradle means the app inherits these
# automatically; nothing has to be copied into android/app/proguard-rules.pro
# (which is generated by prebuild and gitignored anyway).

# The Service and the two BroadcastReceivers are entry points reached only from
# the merged manifest. AGP generates keep rules from the manifest, so this is
# belt-and-braces — but the cost is nil and the failure mode is silence.
-keep class expo.modules.adhanplayback.AdhanPlaybackService { *; }
-keep class expo.modules.adhanplayback.AdhanAlarmReceiver { *; }
-keep class expo.modules.adhanplayback.AdhanBootReceiver { *; }

# AdhanPlaybackService.Companion holds the cross-class statics the module reads
# and writes: `isPlaying` (the single-player guard) and `onFinishedNaturally`
# (the interstitial trigger). Keep the companion and its members so R8 cannot
# inline the backing fields and desynchronise the two classes' view of them.
-keep class expo.modules.adhanplayback.AdhanPlaybackService$Companion { *; }
-keepclassmembers class expo.modules.adhanplayback.AdhanPlaybackService {
    public static ** Companion;
    static ** isPlaying;
    static ** onFinishedNaturally;
}

# AdhanScheduler is a Kotlin `object` invoked from the receivers and the module.
-keep class expo.modules.adhanplayback.AdhanScheduler { *; }
-keep class expo.modules.adhanplayback.AdhanScheduler$* { *; }

# AdhanPlaybackModule itself is instantiated reflectively by expo-modules-core
# from expo-module.config.json. expo-modules-core already ships
# `-keep ... class * extends expo.modules.kotlin.modules.Module`, so this is
# redundant today; it is stated explicitly so the module does not depend on
# another package's keep rules staying as they are.
-keep class expo.modules.adhanplayback.AdhanPlaybackModule { *; }

# ─── RESOURCE SHRINKING (shrinkResources) ────────────────────────────────────
#
# NOT covered by this file — resource shrinking is driven by res/raw/keep.xml,
# not ProGuard rules, and that file is GENERATED by the React Native gradle
# plugin at android/app/build/generated/res/react/<variant>/raw/keep.xml. A
# library cannot contribute to it: an app-level `raw/keep` overrides any
# library's, silently.
#
# The generated keep list protects Metro's copies (@raw/assets_audio_azan, …)
# but NOT the expo-notifications config-plugin copies (@raw/azan, @raw/azan_fajr,
# @raw/azan_mishary, …) — which are the ones this module resolves by name via
# Resources.getIdentifier(). Enabling shrinkResources today would therefore
# strip exactly the resources the service plays.
#
# Rather than depend on a keep rule nobody will remember, AdhanPlaybackService
# resolves `raw/<name>` and falls back to `raw/assets_audio_<name>` — the same
# audio under a name the generated keep.xml already protects. That makes the
# module survive resource shrinking with no keep.xml edit at all. See the
# `resolveSound` note in AdhanPlaybackService.kt.
